name: Generate contribution snake
on:
  push:
    branches: [ "main" ]         # <— NEW: makes it appear after your next commit
  schedule:
    - cron: "0 0 * * *"          # daily (UTC)
  workflow_dispatch:              # run it manually from Actions

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ShanwazWaqar
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
